#!/usr/bin/env python
# coding: utf-8

import sys


POS = {
     1: u'daiktavardis',
     2: u'būdvardis',
     3: u'skaitvardis',
     4: u'įvardis',
     5: u'veiksmažodis',
     6: u'prieveiksmis',
     7: u'dalelytė',
     8: u'prielinksnis',
     9: u'jungtukas',
    10: u'jaustukas',
    11: u'ištiktukas',
}

SOURCES = {
     1: u'DLKŽ72',
     2: u'DLKŽ72 papild',
     3: u'TŽŽ85',
     4: u'TŽŽ85 papild',
     5: u'Kt., pvz., necenzūr. žodžiai ir pan.',
}


PREFIXES = {
    '+':  (u'',   u' leksemos dalis be prefikso'),
    'N':  (u'ne', u'ne-'),
    'N_': (u'n',  u'n(e)-'),
    'B':  (u'be', u'be-'),
    'B_': (u'b',  u'b(e)-'),
    'S':  (u'si', u'si-'),
    'S_': (u's',  u's(i)-'),
    'E':  (u'ap,su', u'elementarus į daiktavadžio prefiksinę dalį įeinantis priešdėlis (ap-, su- ir t.t., išskyrus N, S, B)'),
    'F':  (u'', u'visi elementarūs priešdėliai, išskyrus ap(i)-, at(i)-, par-'),
    'R':  (u'', u'visi elementarūs priešdėliai, išskyrus ap-, at(i)-, par-, tame tarpe ir api- !'),
    'H':  (u'', u'visi elementarūs priešdėliai, išskyrus at(i)-, par-, tame tarpe ir ap-, api- !'),
    'G':  (u'', u'visi elementarūs priešdėliai, išskyrus at(i)-, par-, api-, tame tarpe ir ap- (bet ne api- !)'),
    'K':  (u'', u'visi elementarūs priešdėliai, išskyrus ap(i)-, ati-, tame tarpe ir at- (be įterptinio i !), ir par-.'),
    'ap': (u'ap', u'elementarusis priešdėlis ap- (be i !)'),
    'at': (u'ap', u'elementarusis priešdėlis at- (be i !)'),
}


MORPHOLOGY = {
    # Daiktavardis
    1: [
        (u'Daiktavardžio įpatumai', {
             4: (u'Tikriniškumas', {
                  1: u'Bendrinis',
                  2: u'Asmenvardis-vardas',
                  3: u'Ne tikrinis, bet  "iš pagarbos" ir pan. gali būti traktuojamas (t.y. rašomas iš didžiosios) kaip tikrinis (pvz., Dievas, Altingas, Koranas ir pan.)',
                  4: u'Tikrinis geografinis vardas - miestas, kaimas, šalis, gyvenvietė, t.y. toks, iš kurio galimi vediniai su -ietis(-ė) ir pan.',
                  5: u'Kiti tikriniai vardai, pvz., firmų pavadinimai',
                  6: u'Tikrinis geografinis vardas: upės, ežerai, kalnai ir pan.',
                  7: u'Subendrinėjęs asmenvardis-vardas (gali būti rašomas ir iš mažosios, ir iš didžiosios), pvz., Eskulapas-eskulapas',
                  8: u'Subendrinėjęs tikrinis geografinis vardas (gali būti rašomas tiek mažosios, tiek iš didžiosios), pvz., Kvirinalas-kvirinalas',
                 10: u'Subendrinėjęs kitas tikrinis vardas (pvz., antikinių švenčių), pvz., herėjos-Herėjos',
             }),
             5: (u'Neigiamumas', {
                  1: u'Daiktavardis žodynuose be neigiančio prefikso, neigiančių prefiksų turėti negali',
                  2: u'Turi neigiantį prefiksą a-; be šito prefikso jis nevartojamas; pvz.: alogizmas',
                  3: u'Turi neigiantį prefiksą an-; be šito prefikso jis nevartojamas; pvz...: analfabetizmas',
                  4: u'Turi neigiantį prefiksą a-; yra atitinkamas dktv ir be šito prefikso; pvz...: aneurinas',
                  5: u'Turi neigiantį prefiksą be-; yra atitinkamas dktv ir be šito prefikso; pvz...: besotumas',
                  6: u'Turi neigiantį prefiksą ne-; yra atitinkamas dktv ir be šito prefikso; pvz...: neakivaizdininkas',
                  7: u'Turi neigiantį prefiksą ne-; be šito prefikso jis nevartojamas; pvz...: nerimas',
                  8: u'Turi neigiantį prefiksą be-; be šito prefikso jis nevartojamas; bedalis',
                  9: u'Daiktavardis žodynuose be neigiančio prefikso; gali turėti neigiančius prefiksus ne-, nebe- ir pan.; pvz...: abejingumas-neabejingumas',
             }),
             6: (u'Kiti ypatumai (daiktavardžio pobūdis)', {
                  1: u'Eilinis daiktavardis',
                  2: u'Etnonimas (tautietis)',
                  3: u'Fleksiškai nekaitomas, (paprastai?) kitų kalbų, bendrinis, pvz., kredo',
                  4: u'Teksto vienetas-užsienio k. įterpinys (dažniausiai posakiuose, pvz. lotyniškuose, ir pan.), kuriam lietuvių k. gramatinės kategorijos (giminė, linksnis, kalbos d. ir pan.) neturi prasmės arba turi ją sąlyginai; priskyrimas daiktavardžiams [dažniausiai] irgi yra sąlyginis; pvz.: allegro, coupe, entree',
                  5: u'Vyriškos giminės "moteriškai" linksniuojamas, žr. DLKG97 §104 e) ir f)',
                  6: u'Vyriškos giminės, sudaiktavardėjęs iš būdvardžio, pvz jaunasis',
                  7: u'Vyriškos giminės, sudaiktavardėjęs iš dalyvio, pvz., išrinktasis, palaimintasis, pažįstamas, laukiamasis, mylimasis, kaltinamasis, nežinomasis, dirbantysis, suaugęs',
                  8: u'Moteriškos giminės, sudaiktavardėjęs iš būdvardžio, pvz., jaunoji, gulsčioji, baltosios, lygiosios',
                  9: u'Moteriškos giminės, sudaiktavardėjęs iš dalyvio, pvz., palaimintoji, pažįstama, kertamoji, kuliamoji, mylimoji, dirbančioji, sprogtinoji',
                 10: u'Bendrosios giminės "vyriškai" linksniuojamas',
                 11: u'Bendrosios giminės "moteriškai" linksniuojamas',
             }),
        }),
        (u'Kaitybos charakteristika', {
             7: (u'Linksniavimo charakteristika', {
                  0: u'Daiktavardis nekaitomas, nelinksniuojamas',
                  1: u'(i)a linksniuotė, paradigma nr. 1 (žiūr DLKG97 psl.70)',
                  2: u'(i)a linksniuotė, paradigma nr. 2 (žiūr DLKG97 psl.71)',
                  3: u'(i)a linksniuotė, paradigma nr. 3 (žiūr DLKG97 psl.71)',
                  4: u'(i)u linksniuotė, paradigma nr. 4 (žiūr DLKG97 psl.72)',
                  5: u'(i)u linksniuotė, paradigma nr. 5 (žiūr DLKG97 psl.73)',
                  6: u'(i)o linksniuotė, paradigma nr. 6 (žiūr DLKG97 psl.74)',
                  7: u'(i)o linksniuotė, paradigma nr. 7 (žiūr DLKG97 psl.74)',
                  8: u'ė linksniuotė, paradigma nr. 8 (žiūr DLKG97 psl.75)',
                  9: u'i linksniuotė, paradigma nr. 9 (žiūr DLKG97 psl.76)',
                 10: u'i linksniuotė, paradigma nr. 10(žiūr DLKG97 psl.77)',
                 11: u'i linksniuotė, paradigma nr. 11(žiūr DLKG97 psl.77)',
                 12: u'i linksniuotė, paradigma nr. 12(žiūr DLKG97 psl.78)',
                 13: u'Paradigma daiktavardžiui petys;',
                 14: u'Paradigma daiktavardžiui žmogus (žmonės);',
                 15: u'Paradigma daiktavardžiui pats;',
                 16: u'Paradigma daiktavardžiui viešpats;',
                 17: u'Paradigma daiktavardžiui mėnuo;',
                 18: u'Paradigma vyr. g. daiktavardžiams iš sudaiktavardėjusių įvardžiuotinių būdvardžių bei dalyvių su -asis, pvz., jaunasis, palaimintasis, miegamasis, laukiamasis, mylimasis, nežinomasis',
                 19: u'Paradigma vyr. g. daiktavardžiams iš sudaiktavardėjusių įvardžiuotinių būdvardžių ar dalyvių su -[t]ysis, pvz., pėstysis, vyresnysis, dirbantysis',
                 20: u'Paradigma vyr. g. daiktavardžiams iš sudaiktavardėjusių neįvardžiuotinių dalyvių su -[..]as, pvz., pažįstamas',
                 21: u'Paradigma vyr. g. daiktavardžiams iš sudaiktavardėjusių neįvardžiuotinių dalyvių su -ęs, pvz., suaugęs',
                 22: u'Paradigma mot. g. daiktavardžiams iš sudaiktavardėjusių įvardžiuotinių būdvardžių bei dalyvių su -(i)oji, pvz., jaunoji, palaimintoji, gulsčioji, kaltinamoji, kuliamoji, mylimoji, dirbančioji, sprogtinoji',
                 23: u'Paradigma vyr. g. sangrąžiniams daiktavardžiams iš sangrąžinių veiksmažodžių su ‑asis, pvz., barimasis(-osi, -uisi, ...)',
             }),
             8: (u'Giminės charakteristika', {
                  1: u'Eilinis vyr. gim. daiktavardis',
                  2: u'Vyr. gim. dktv; turi atitikmenį mot. gim., pvz., informatikas->informatikė',
                  3: u'Daiktavardis nekaitomas; tradiciškai laikoma, kad tai vyr. gim., nors tai ne visais atvejais akivaizdu., pvz., kredo, taksi',
                  4: u'Dažniausiai [tradiciškai?] laikoma, kad daiktavardis yra vyr. gim., bet iš principo (teoriškai) jis gali būti tiek vyr., tiek ir mot.giminės, pvz., kai kurie nekaitomi dktv: buržua, atašė, portjė ar kaitomi: junga, buožė ',
                  5: u'Eilinis mot. gim. daiktavardis',
                  6: u'Eilinis bendr. gim. daiktavardis',
                  7: u'Daiktavardis nekaitomas; gali būti laikoma, kad tai mot. gim., nors tai ne visais atvejais akivaizdu; pvz.: bezė',
                  8: u'Mot. gim. daiktavardis; turi atitikmenį vyr. gim. pvz., aulininkė->aulininkas',
                  9: u'Daiktavardis nekaitomas; apie jo giminę ką nors pasakyti sunku (teksto vienetai-užsienio k. įterpiniai ir kt.)',
             }),
             9: (u'Skaičiaus charakteristika', {
                  0: u'Daiktavardis nekaitomas, (gali būti laikoma, kad) skaičiaus kategorijos neturi',
                  1: u'Normalus abiskaitinis, pvz., namas',
                  2: u'Abiskaitinis "tipo analgetikai": nors žodynuose (dažniausiai) pateikiamas daugiskaitoje, gali įgyti ir "normalias" vienaskaitos formas, pvz., analgetikai-analgetikas',
                  3: u'Daugiskaitinis, pvz., miltai, žirklės',
                  4: u'"Normalus" vienaskaitinis',
                  5: u'"Labiau vienaskaitinis" nei abiskaitinis, nes tai tikrinis vardas, pvz., Achilas',
                  6: u'"Labiau daugiskaitinis" nei abiskaitinis, pvz. Parkos (tikrinis iš TŽŽ)',
             }),
            10: (u'Sangrąžiškumo charakteristika', {
                  0: u'Daiktavardis neturi sangrąžiškumo požymio (=sangrąžiškumo požymis daiktavardžiui neturi prasmės), pvz., namas',
                  # Padarytiems iš veiksmažodžių daiktavardžiams:
                  1: u'Žodynuose (paprastai) pateikiamas nesangrąžinis, tačiau galimos ir sangrąžinės formos, pvz., apgulimas',
                  2: u'Žodynuose pateikiamas nesangrąžinis, sangrąžinių formų neturi (arba sangrąžiškumo požymio daiktavardis iš vis neturi, o čia kalbam apie sangrąžiškumą dėl to, kad dktv padarytas iš veiksmažodžio), pvz., liudijimas, mokytojas',
                  3: u'Žodynuose pateikiamas sangrąžinis; nesangrąžinių formų neturi, pvz., juokimasis, kėsinimasis',
            }),
        }),
        (u'Darybos charakteristika', {
            11: (None, {
                  0: u'pamatinis, nepadarytas iš nieko daiktavardis: namas',
                  1: u'padarytas iš daiktavardžio su priesaga -ininkas[ė]: aulininkas',
                  2: u'mažybinis, padarytas iš daiktavardžio su priesaga -elis[ė]: balnelis',
                  3: u'padarytas iš daiktavardžio su priesaga -ingumas: balsingumas',
                  4: u'padarytas iš daiktavardžio su priesaga -ystė',
                  5: u'mažybinis, padarytas iš daiktavardžio su priesaga -iokas[ė]: berniokas',
                  6: u'mažybinis, padarytas iš daiktavardžio su priesaga -iukas[ė]: berniukas',
                  7: u'mažybinis, padarytas iš daiktavardžio su priesaga -iūkštis[tė]: berniūkštis',
                  8: u'mažybinis, padarytas iš daiktavardžio su priesaga -ytis[tė]: bernytis',
                  9: u'mažybinis, padarytas iš daiktavardžio su priesaga -užis[ė]: bernužis',
                 10: u'mažybinis, padarytas iš daiktavardžio su priesaga -aitis[tė]: dievaitis',
                 11: u'padarytas iš daiktavardžio su priesaga -iškumas: dieviškumas',
                 12: u'mažybinis, padarytas iš daiktavardžio su priesaga -ukas[ė]: dievukas',
                 13: u'mažybinis, padarytas iš daiktavardžio su priesaga -utis[tė]: gužutis',
                 14: u'mažybinis, padarytas iš daiktavardžio su priesaga -ėkas[ė]: paršėkas',
                 15: u'mažybinis, padarytas iš daiktavardžio su priesaga -ėlis[ė]: avinėlis',
                 16: u'mažybinis, padarytas iš daiktavardžio su priesaga -okas[ė]: bėrokas',
                 17: u'mažybinis, padarytas iš daiktavardžio su priesaga -elytis[tė]: žodelytis',
                 18: u'mažybinis, padarytas iš daiktavardžio su priesaga -ulis[ė]: tėtulis',
                 19: u'padarytas iš daiktavardžio su priesaga -ie-tis[tė]: azerbaidžanietis',
                 20: u'padarytas iš daiktavardžio su priesaga -iškis[ė]: birštoniškė',
                 21: u'mažybinis, padarytas iš daiktavardžio su priesaga -ikė[is?]: mergikė',
                 22: u'mažybinis, padarytas iš daiktavardžio su priesaga -io-tė[tis?]: mergiotė',
                 23: u'padarytas iš būdvardžio su priesaga -umas: abipusiškumas',
                 24: u'padarytas iš būdvardžio su priesaga -ybė: akylybė',
                 25: u'padarytas iš daiktavardžio su priesaga -ingumas ir su priešdėliu ne-: neturtingumas',
                 26: u'padarytas iš daiktavardžio su priesaga -ystė ir su priešdėliu ne-: neturtystė',
                 27: u'padarytas iš daiktavardžio su priesaga -iškumas ir su priešdėliu be-: beglobiškumas',
                 28: u'padarytas iš daiktavardžio su priesaga -ystė ir su priešdėliu be-: bepinigystė',
                 29: u'padarytas iš daiktavardžio su priesaga -ininkas[ė] ir su priešdėliu ne-: nepriemokininkas',
                 30: u'mažybinis, padarytas iš daiktavardžio su priesaga -ėlis[ė] ir su priešdėliu ne-: nelaimėlė',
                 31: u'padarytas iš daiktavardžio su priesaga -iškumas ir su priešdėliu ne-: nemokšiškumas',
                 32: u'padarytas iš daiktavardžio su priesaga -umas ir su neig. pref. a-: apolitiškumas',
                 33: u'padarytas iš būdvardžio su priesaga -umas ir su priešdėliu be-: beidėjiškumas',
                 34: u'padarytas iš būdvardžio su priesaga -umas ir su priešdėliu ne-: nedorumas',
                 35: u'padarytas iš būdvardžio su priesaga -iškumas: savitarpiškumas',
                 36: u'padarytas iš būdvardžio su priesaga -ybė ir su priešdėliu be-: bekraštybė',
                 37: u'padarytas iš skaitvardžio su priesaga -ybė: pirmenybė',
                 38: u'padarytas iš skaitvardžio su priesaga -umas: pirmumas',
                 39: u'mažybinis, padarytas iš skaitvardžio su priesaga -ukas[ė]: vienetukas, vienukė',
                 40: u'padarytas iš skaitvardžio su priesaga -ystė: vienystė',
                 41: u'mažybinis, padarytas iš skaitvardžio su priesaga -utėlis: vienutėlis',
                 42: u'mažybinis, padarytas iš skaitvardžio su priesaga -utis: vienutis',
                 43: u'mažybinis, padarytas iš skaitvardžio su priesaga -utukas: vienutukas',
                 44: u'padarytas iš skaitvardžio su priesaga -ulė[is?]: trijulė',
                 45: u'mažybinis, padarytas iš skaitvardžio su priesaga -iukė[as?]: šešiukė',
                 46: u'padarytas iš įvardžio su priesaga -umas: saviškumas',
                 47: u'padarytas iš veiksmažodžio su -imas(ymas)  plius su priešdėliu ap-: apgulimas',
                 48: u'padarytas iš veiksmažodžio su -imas(ymas)  plius su prefiksu apsi-: apsikalimas',
                 49: u'padarytas iš veiksmažodžio su -imas(-imasis) (be prefikso)',
                 50: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu iš-: išbarimas',
                 51: u'padarytas iš veiksmažodžio su -inėjimas  plius su priešdėliu iš-: iškalinėjimas',
                 52: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu į-: įgnybimas',
                 53: u'padarytas iš veiksmažodžio su -ėjas(a) (be prefikso)',
                 54: u'padarytas iš veiksmažodžio su -ikas(ė) (be prefikso)',
                 55: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu nu-: nugulimas',
                 56: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu pa-: pabarimas',
                 57: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu per-: perkalimas',
                 58: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu pra-: prakalimas',
                 59: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu pri-: prigulimas',
                 60: u'padarytas iš veiksmažodžio su -inėjimas  plius su priešdėliu pri-: prikalinėjimas',
                 61: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu su-: sugulimas',
                 62: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu už-: užgulimas',
                 63: u'padarytas iš veiksmažodžio su -inėjimas  plius su priešdėliu už-: užkalinėjimas',
                 64: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu užsi-: užsigulimas',
                 65: u'padarytas iš veiksmažodžio su -ėjas(a)  plius su priešdėliu ap-: apdirbėja',
                 66: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu at-: atlupimas',
                 67: u'padarytas iš veiksmažodžio su -inėjimas(-inėjimasis ?) (be prefikso)',
                 68: u'padarytas iš veiksmažodžio su -tinumas (be prefikso)',
                 69: u'padarytas iš veiksmažodžio su -ėjas(a)  plius su priešdėliu iš-: išdirbėja',
                 70: u'padarytas iš veiksmažodžio su -ėjas(a)  plius su priešdėliu pa-: padirbėja',
                 71: u'padarytas iš veiksmažodžio su -inėjimas  plius su priešdėliu pa-: padirbinėjimas',
                 72: u'padarytas iš veiksmažodžio su -inėjimas  plius su priešdėliu per-: perdirbinėjimas',
                 73: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu persi-: persidirbimas',
                 74: u'padarytas iš veiksmažodžio su -tojas(a) (be prefikso): aiškintojas',
                 75: u'padarytas iš veiksmažodžio su -tojas(a)  plius su priešdėliu ap-: apdulkintoja',
                 76: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu api-: apibendrinimas',
                 77: u'padarytas iš veiksmažodžio su -imas  plius su priešdėliu ati-: atitolinimas',
                 78: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu atsi-: atsisveikinimas',
                 79: u'padarytas iš veiksmažodžio su -tojas(a)  plius su priešdėliu iš-: išaiškintojas',
                 80: u'padarytas iš veiksmažodžio su -tojas(a)  plius su priešdėliu į-: įdukrintojas',
                 81: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu įsi-: įsigilinimas',
                 82: u'padarytas iš veiksmažodžio su -[(i)a,i,o]mumas  plius su prefiksu nepa-: nepakaltinamumas',
                 83: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu nusi-: nusigyvenimas',
                 84: u'padarytas iš veiksmažodžio su -tojas(a)  plius su priešdėliu pa-: pagreitintoja',
                 85: u'padarytas iš veiksmažodžio su -[(i)a,i,o]mumas  plius su prefiksu pa-: pakaltinamumas, pastebimumas',
                 86: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu par-: pargabenimas',
                 87: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu pasi-: pasiaiškinimas',
                 88: u'iš vksm su -toj-as(a)  plius su prefiksu pasi-: pasisavintoja',
                 89: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu prasi-: prasigyvenimas',
                 90: u'padarytas iš veiksmažodžio su -imas  plius su prefiksu prisi-: prisigretinimas',
                 91: u'mažybinis, padarytas iš vksm su -tojėlis(ė) (be prefikso)',
                 92: u'padarytas iš veiksmažodžio su -[(i)a,i,o]mumas  plius su prefiksu su-: sugyvenamumas',
                 93: u'iš vksm su -tojas(a) su pa-: suniekintintoja',
                 94: u'iš vksm su -imas su susi-: susirūpinimas',
                 95: u'iš vksm su -[(i)a,i,o]mumas bepref: virškinamumas, tariamumas, regimumas',
                 96: u'iš vksm su -inėjimas su į-: įtarinėjimas',
                 97: u'iš vksm su -imas su nesu-: nesutarimas',
                 98: u'iš vksm su -[(i)a,i,o]myb-ė bepref: tariamybė,regimybė',
                 99: u'iš vksm su -ėjas(a) su už-: užgrobėjas',
                100: u'iš vksm su -ikas(ė) su už-: užgrobikas',
                101: u'iš vksm su -telėjimas bepref: aiktelėjimas',
                102: u'iš vksm su -terėjimas bepref: aisterėjimas',
                103: u'iš vksm su -tybė su at-: atsietybė',
                104: u'iš vksm su -imas su išsi-: išsiliejimas',
                105: u'iš vksm su -tojas(a) su per-: perįgaliotojas',
                106: u'iš vksm su -tojas(a) su pra-: praleidinėtojas',
                107: u'iš vksm su -tojas(a) su už-: užrašinėtojas',
                108: u'iš vksm su -imas(-imasis) ir su be-: bedievėjimas',
                109: u'iš vksm su -[(i)a,i,o]mumas su neį-: neįkainojamumas, neįtikimumas',
                110: u'iš vksm su -tojas(a) su par-: pardavinėtojas',
                111: u'iš vksm su -tojas(a) su pri-: prigaudinėtojas',
                112: u'iš vksm su -[(i)a,i,o]mumas su ne-: nemirštamumas',
                113: u'iš vksm su -inėjimas su at-: atkalbinėjimas',
                114: u'iš vksm su -[(i)a,i,o]myb-ė su ne-: nejudamybė',
                115: u'iš vksm su -ėjas(a) su pra-: pradėjėjas',
                116: u'iš vksm su -[(i)a,i,o]mybė su iš-: ištikimybė',
                117: u'iš vksm su -[(i)a,i,o]mumas su iš-: ištikimumas',
                118: u'iš vksm su -[(i)a,i,o]mybė su į-: įtikimybė',
                119: u'iš vksm su -[(i)a,i,o]mumas su į-: įtikimumas',
                120: u'iš vksm su -tinumas su ne-: netikėtinumas',
                121: u'iš vksm su -tybė su ne-: netikėtybė',
                122: u'iš vksm su -(ė)tumas su ne-: netikėtumas',
                123: u'iš vksm su -[(i)a,i,o]mybė su pa-: patikimybė',
                124: u'iš vksm su -[(i)a,i,o]mumas su per-: perregimumas,pereinamumas',
                125: u'iš vksm su -imas su neapsi-: neapsižiūrėjimas',
                126: u'iš vksm su -tojas(a) su nu-: nugalėtojas',
                127: u'iš vksm su -inėjimas su pasi-: pasibėginėjimas',
                128: u'iš vksm su -tumas bepref: baigtumas',
                129: u'iš vksm su -ėjas(a) su į-: įdiegėjas',
                130: u'iš vksm su -[(i)a,i,o]myb-ė su nepa-: nepabaigiamybė',
                131: u'iš vksm su -ėjas(a) su per-: perjungėjas',
                132: u'iš vksm su -tinumas su pri-: primygtinumas',
                133: u'iš vksm su -[(i)a,i,o]myb-ė su neiš-: neišvengiamybė',
                134: u'iš vksm su -[(i)a,i,o]mumas su neiš-: neišvengiamumas',
                135: u'iš vksm su -[(i)a,i,o]mumas su nepri-: neprieinamumas',
                136: u'iš vksm su -[(i)a,i,o]myb-ė su par-: pareinamybė',
                137: u'iš vksm su -[(i)a,i,o]mumas su par-: pareinamumas',
                138: u'iš vksm su -[(i)a,i,o]mumas su pra-: praeinamumas',
                139: u'iš vksm su -[(i)a,i,o]mumas su pri-: prieinamumas',
                140: u'iš vksm su -inėjimas su ap-: apsakinėjimas',
                141: u'iš vksm su -[(i)a,i,o]mybė su at-: atsakomybė',
                142: u'iš vksm su -inėjimas su atsi-: atsiprašinėjimas',
                143: u'iš vksm su -[(i)a,i,o]mumas su neati-: neatitaisomumas',
                144: u'iš vksm su -[(i)a,i,o]myb-ė su neiš-: nepriklausomybė',
                145: u'iš vksm su -[(i)a,i,o]mumas su nesu-: nesulaikomumas',
                146: u'iš vksm su -inėjimas su nu-: nudarinėjimas',
                147: u'iš vksm su -toj-as(a) su prasi-: prasimanytojas',
                148: u'iš vksm su -[(i)a,i,o]myb-ė su pri-: priklausomybė',
                149: u'iš vksm su -inėjimas su su-: surašinėjimas',
                150: u'iš vksm su -inėjimas su susi-: susirašinėjimas',
                151: u'iš vksm su -tybė su ati-: atitrauktybė',
                152: u'iš vksm su -inėjimas su išsi-: išsisukinėjimas',
                153: u'iš vksm su -tinybė su atsi-: atsitiktinybė',
                154: u'iš vksm su -tinumas su atsi-: atsitiktinumas',
                155: u'iš vksm su -imas su ne-: netekimas',
                156: u'iš vksm su -[(i)a,i,o]mumas su už-: užtenkamumas',
                157: u'iš vksm su -ėjas(a) su su-: surinkėjas',
                158: u'iš vksm su -tinumas su iš-: išimtinumas',
                159: u'iš vksm su -ėjas(a) su pri-: priėmėja',
                160: u'iš vksm su -ikas(ė) su iš-: išdavikas',
                161: u'iš vksm su -ikas(ė) su į-: įdavikas',
                162: u'iš vksm su -ėjas(a) su par-: pardavėja',
                163: u'iš vksm su -ikas(ė) su par-: pardavikas',
                164: u'iš vksm su -inėjimas su par-: pardavinėjimas',
                165: u'iš vksm su -tumas su su-: suinteresuotumas',
                166: u'iš vksm su -ėjas(a) su at-: atradėjas',
                167: u'iš vksm su -tumas su ap-: apšviestumas',
                168: u'iš vksm su -ėjas(a) su nu-: nuleidėjas',
                169: u'iš vksm su -inėjimas su pra-: praleidinėjimas',
                170: u'iš vksm su -inėjimas su apsi-: apsimetinėjimas',
                171: u'iš vksm su -imas su nesusi-: nesusipratimas',
                172: u'iš vksm su -[(i)a,i,o]mumas su nenu-: nenuilstamumas',
                173: u'iš vksm su -ikas(ė) su pri-: prigavikas',
                174: u'iš vksm su -tinybė bepref: būtinybė',
                175: u'iš vksm su -tybė bepref: būtybė',
                176: u'iš ištikt su -telėjimas: pakštelėjimas',
            }),
        }),
        (u'Derivacijos charakteristika', {
            12: (u'Demunityviniai vediniai', {
                  1: u'Deminutyvų neturi',
                  2: u'Turi normalius deminutyvus; deminutyvų abiejose giminėse (kaip kad pvz. meška-meškutis-meškutė) neturi',
                  3: u'Turi deminutyvus abiejose giminėse, pvz., meška-meškutis-meškutė',
                  4: u'Daiktavardžiai nekaitomi (nėra linksniuojami), nors kai kurie jų, ypač dažniau vartojami ir ypač šnek. kalboje, "lietuviškas" kai kurių linksnių galūnes gali ir įgyti; laikom, kad kai kurie tokie nekait. dktv. kartais gali įgyti mažybines formas, bet kaip būtent mažybinės priesagos prie tokių nekait. dktv. "lipdomos", šiame darbo etape toks suklasifikavimas daromas nebuvo (tai [galbūt] yra ateities etapų užduotis), pvz., atašė, buržua',
                  5: u'Kaip ir 2 (turi normalius deminutyvus; deminutyvų abiejose giminėse neturi); tik: pats jau yra mažybinis, pvz., balnelis (dviračio)',
            }),
            13: (u'Daiktavardžio vedinių su -ininkas(-ė) galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            14: (u'Daiktavardžio vedinių su -ybė galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            15: (u'Daiktavardžio vedinių su -ystė galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            16: (u'Būdvardžio vedinių su -ingas galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            17: (u'Būdvardžio vedinių su -iškas galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            18: (u'Būdvardžio vedinių su -inis galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            19: (u'Prieveiksmio vedinių su -in(i)ai galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            20: (u'vedinių su -ėtas galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            21: (u'Būdvardžio vedinių su -(u)otas galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            22: (u'Prefiksiniai vediniai', {
                 0: u'',
                 1: u'E,N/E;E/S,N/E/S',
                 2: u'E,N/E;',
                 3: u';E/S,N/E/S',
                 4: u'+,N;',
                 5: u';+,N/S',
                 6: u'+,N;+,N/S',
                 7: u'+,N,F,N/F;+,N/S,F/S,N/F/S',
                 8: u'E,N/E;ap/S,N/ap/S',
                 9: u'E,N/E;at/S,N/at/S',
                10: u'+,N,F,N/F;',
                11: u'+,B;',
                12: u'N/E;',
                13: u'+,N,R,N/R;',
                14: u'N;',
                15: u'E,N/E;E/S_,N/E/S_',
                16: u'+, N_,N/B_;+, N/S_,N/B/S_',
                17: u'+,N;N,N/S',
                18: u';+,N/S,F/S,N/F/S',
                19: u'+,N,H,N/H;N/S,G/S,N/G/S',
                20: u'+,N,G,N/G;+,N/S,G/S,N/G/S',
                21: u'+,N,K,N/K;',
                22: u'+,N;',
            }),
        }),
    ],

    # Būdvardis
    2: [
        (u'Kaitybos charakteristika', {
             4: (u'Linksniavimo charakteristika', {
                  0: u'Būdvardis nekaitomas, nelinksniuojamas, pvz.: bordo',
                  1: u'(i)a linksniuotė, paradigma nr. 1 (žiūr DLKG97 psl.179), pvz.: geras',
                  2: u'(i)a linksniuotė, paradigma nr. 2 (žiūr DLKG97 psl.179), pvz.: žalias',
                  3: u'(i)a linksniuotė, paradigma nr. 3 (žiūr DLKG97 psl.179-180), pvz.: kairys, paskesnis',
                  4: u'(i)a linksniuotė, paradigma nr. 4 (žiūr DLKG97 psl.180), pvz.: paskutinis',
                  5: u'(i)u linksniuotė, paradigma nr. 5 (žiūr DLKG97 psl.181), pvz.: gražus',
                  6: u'Paradigma būdvardžiui vėlus, pvz.: vėlus(-as)',
                  7: u'Paradigma būdvardžiams iš subūdvardėjusių veik. r. esamojo l. dalyvių su  -antis, ‑intis, pvz.: sekantis, pasiturintis',
                  8: u'Paradigma būdvardžiams iš subūdvardėjusių veik. r. būtojo l. dalyvių su  -ęs, pvz.: pasileidęs',
                  9: u'Paradigma būdvardžiams iš subūdvardėjusių neveik. r. esamojo l. įvardžiuotinių dalyvių su [-(i)am-, -im-, -om-] +  -asis, pvz.: patariamasis, stojamasis, mokomasis',
                 10: u'Paradigma būdvardžiams iš subūdvardėjusių neveik. r. būtojo l. įvardžiuotinių dalyvių su  -tasis, pvz.: išrinktasis',
                 11: u'Paradigma būdvardžiui iš skaitvardžio abu su  -oks, pvz.: abejoks',
             }),
             5: (u'Laipsniavimo charakteristika', {
                 0: u'Būdvardis nekaitomas, nelaipsniuojamas; gali būti laikoma, kad laipsnio kategorijos neturi arba kad yra nelyginamojo laipsnio, pvz.: bordo',
                 1: u'laipsniuojamas, įgyja visus laipsnius, pvz.: gražus',
                 2: u'nelaipsniuojamas; žodynuose pateikiamas nelyginamojo laipsnio, pvz.: aukštielninkas',
                 3: u'nelaipsniuojamas; žodynuose pateikiamas aukščiausiojo laipsnio, pvz.: apačiausias',
                 4: u'laipsniuojamas, bet nelyg. lpsn. neturi; žodynuose pateikiamas aukštesniojo laipsnio, pvz.: paskesnis',
                 5: u'laipsniuojamas, bet nelyg. lpsn. neturi; žodynuose pateikiamas aukščiausiojo laipsnio, pvz.: viršiausias',
                 6: u'laipsniuojamas, bet nelyg. lpsn. neturi; žodynuose pateikiamas aukštėlesniojo laipsnio, pvz.: viršėlesnis',
             }),
             6: (u'Apibrėžtumas (įvardžiuotinumas)', {
                 0: u'būdvardis nekaitomas: apibrėžtumo požymio neturi, pvz.: bordo',
                 1: u'įgyja ir neįvardžiuotines, ir įvardžiuotines formas; žodynuose pateikiamas neįvardžiuotinės formos, pvz.: gražus',
                 2: u'įgyja ir neįvardžiuotines, ir įvardžiuotines formas; žodynuose pateikiamas įvardžiuotine forma, pvz.: gotiškasis',
                 3: u'nelyg. laipsnyje turi tik neįvardžiuotines formas; kituose - ir tokias, ir tokias, pvz.: didelis: didesnis,  ‑esnysis, ‑iausiasis',
                 4: u'turi tik neįvardžiuotines formas, pvz.: dvišakas',
                 5: u'žodynuose pateikiamas įvardžiuotine forma; turi tik įvardžiuotines formas, pvz.: taikomasis',
             }),
             7: (u'Kaitymas gimine', {
                 0: u'būdvardis nekaitomas; galima laikyti, kad giminės kategorijos neturi, pvz.: bordo',
                 1: u'turi visas gimines: vyr., mot., bevard., pvz.: gražus',
                 2: u'įgyja visas gimines (teoriškai) - vyr., mot., bevard.; žodynuose pateikiamas ir paprastai vartojamas moteriškąja gimine, pvz.: nėščia',
                 3: u'įgyja vyr., mot. gim; bevardės neturi, pvz.: baltažiedis',
                 4: u'turi vyr, mot. gim. (bevard. neturi); žodynuose pateikiamas ir paprastai vartojamas moteriškąja gimine, pvz.: barbitūrinė, šviežiapienė',
                 5: u'įgyja visas gimines: vyr., mot., bevard.; išskyrus nelyginamąjį laipsnį, kuriame bevardės giminės nėra, pvz.: kairys, dešinys',
             }),
             8: (u'Prefiksavimas', {
                 0: u'žodynuose pateikiamas be neig. prefikso; neigiamų formų neturi, pvz.: ekstra, bruto',
                 1: u'žodynuose pateikiamas be neig. prefikso; gali turėti: beprefiksines formas, formas su ne- , nebe- , tebe- ir t.t., pvz.: gražus: gražus; negražus, nebegražus, tebegražus',
                 2: u'žodyne pateiktas su neig. prefiksu a-; vartojamas ir be šito prefikso; gali turėti: beprefiksines formas, formas su a-, formas su ne-, nebe-, tebe- ir t.t., pvz.: atipiškas: tipiškas; atipiškas; netipiškas, nebetipiškas, tebetipiškas ir t.t.',
                 3: u'žodyne pateiktas su neig. prefiksu be-; vartojamas ir be šito prefikso; gali turėti: beprefiksines formas, formas su be-, formas su ne-, nebe-, tebe- ir t.t., pvz.: beatodairiškas: atodairiškas; beatodairiškas; neatodairiškas, nebeatodairiškas, tebeatodairiškas ir t.t.',
                 4: u'žodyne pateiktas su neig. prefiksu be-; be šito prefikso jis nevartojamas; gali turėti: formas su be-, formas su nebe-, tebebe- ir t.t.:  , pvz.: beširdiškas: nebeširdiškas-nebebeširdiškas ir t.t.',
                 5: u'žodyne pateiktas su neig. prefiksu ne-; vartojamas ir be šito prefikso; gali turėti: beprefiksines formas, formas su ne- , nebe- , tebe- ir t.t., pvz.: neblogas: blogas-neblogas-nebeblogas-tebeblogas ir t.t.',
                 6: u'žodyne pateiktas su neig. prefiksu ne-; be šito prefikso jis nevartojamas; gali turėti: formas su ne-, formas su tebene- , pvz.: nerimastingas: nerimastingas-tebenerimastingas',
                 7: u'žodyne pateiktas su neig. prefiksu anti-; vartojamas ir be šito prefikso; gali turėti: beprefiksines formas, formas su anti-, formas su neanti- , nebeanti- , tebeanti- ir t.t., pvz.: antihigieninis: higieninis, antihigieninis, neantihigieninis-nebeantihigieninis, tebeantihigieninis ir t.t.',
             }),
             9: (u'Darybos charakteristika', {
                  0: u'pamatinis, nepadarytas iš nieko būdvardis, pvz.: geras',
                  1: u'padarytas iš daiktavardžio su priesaga ‑iškas, pvz.: angliškas',
                  2: u'padarytas iš daiktavardžio su priesaga ‑inis, pvz.: auksinis',
                  3: u'padarytas iš daiktavardžio su priesaga ‑uotas, pvz.: ginkluotas',
                  4: u'padarytas iš daiktavardžio su priesaga ‑ingas, pvz.: grėsmingas',
                  5: u'padarytas iš daiktavardžio su priesaga ‑ėtas, pvz.: kaulėtas',
                  6: u'padarytas iš daiktavardžio su priesaga ‑ietiškas, pvz.: rytietiškas',
                  7: u'padarytas iš daiktavardžio su priesaga ‑otas, pvz.: pilvotas',
                  8: u'mažybinis, padarytas iš būdvardžio su priesaga ‑utėlis, pvz.: aklutėlis',
                  9: u'padarytas iš būdvardžio su priešdėliu apy‑, pvz.: apymažis',
                 10: u'padarytas iš būdvardžio su priesaga ‑okas, pvz.: mažokas',
                 11: u'mažybinis, padarytas iš būdvardžio su priesaga ‑ėlis, pvz.: mažėlis',
                 12: u'mažybinis, padarytas iš būdvardžio su priesaga ‑iukas, pvz.: mažiukas',
                 13: u'mažybinis, padarytas iš būdvardžio su priesaga ‑iulis, pvz.: mažiulis',
                 14: u'mažybinis, padarytas iš būdvardžio su priesaga ‑ylis, pvz.: mažylis',
                 15: u'mažybinis, padarytas iš būdvardžio su priesaga ‑ytis, pvz.: mažytis',
                 16: u'mažybinis, padarytas iš būdvardžio su priesaga ‑utis, pvz.: mažutis',
                 17: u'mažybinis, padarytas iš būdvardžio su priesaga ‑utytis, pvz.: mažutytis',
                 18: u'mažybinis, padarytas iš būdvardžio su priesaga ‑ytėlis, pvz.: plonytėlis',
                 19: u'padarytas iš būdvardžio su priešdėliu po‑, pvz.: pomažis',
                 20: u'padarytas iš būdvardžio su priešdėliu prie‑, pvz.: priekvailis',
                 21: u'mažybinis, padarytas iš būdvardžio su priesaga ‑utėlaitis, pvz.: sausutėlaitis',
                 22: u'mažybinis, padarytas iš būdvardžio su priesaga ‑ulis, pvz.: apskritulis',
                 23: u'mažybinis, padarytas iš būdvardžio su priesaga ‑ytėlaitis, pvz.: baltytėlaitis',
                 24: u'mažybinis, padarytas iš būdvardžio su priesaga ‑užėlis, pvz.: raitužėlis (KZ kld)',
                 25: u'padarytas iš būdvardžio su ‑ut, pvz.: naujut',
                 26: u'padarytas iš būdvardžio su priesaga ‑iškas, pvz.: savitarpiškas',
                 27: u'padarytas iš skaitvardžio su priesaga ‑inis, pvz.: pirminis',
                 28: u'padarytas iš skaitvardžio su priesaga ‑opas, pvz.: vieneriopas',
                 29: u'padarytas iš skaitvardžio su priesaga ‑gubas, pvz.: viengubas',
                 30: u'padarytas iš skaitvardžio su priesaga ‑linkas, pvz.: vienlinkas',
                 31: u'padarytas iš skaitvardžio su priesaga ‑oks, pvz.: abejoks',
                 32: u'padarytas iš skaitvardžio su priesaga ‑ainis, pvz.: dvejetainis',
                 33: u'padarytas iš skaitvardžio su priesaga ‑gubinis, pvz.: dvigubinis',
                 34: u'padarytas iš įvardžio su priesaga ‑iškas, pvz.: jūsiškas',
                 35: u'padarytas iš įvardžio su priesaga ‑opas, pvz.: keleriopas',
                 36: u'padarytas iš įvardžio su priesaga ‑gubas, pvz.: keliagubas',
                 37: u'padarytas iš įvardžio su priesaga ‑inis, pvz.: kelintinis',
                 38: u'subūdvardėjęs, iš dalyvio, pvz.: sukalbamas, užkrečiamas, suaugęs, išrinktasis',
                 39: u'padarytas iš ko nors su priešdėliu a-, pvz.: atipiškas',
                 40: u'padarytas iš ko nors su priešdėliu be-, pvz.: beatodairiškas',
                 41: u'padarytas iš ko nors su priešdėliu ne-, pvz.: neblogas',
                 42: u'subūdvardėjęs iš dalyvio; plius su priešd. ne-, pvz.: nesukalbamas, neabejojamas, nelyginamasis',
                 43: u'padarytas iš būdvardžio su priesaga -elis, pvz.: didelis',
                 44: u'padarytas iš ko nors su priešdėliu anti-, pvz.: antihigieninis',
                 45: u'padarytas iš daiktavardžio su priesaga -ingas; plius su neigiamu priešdėliu ne-, pvz.: neturtingas',
                 46: u'padarytas iš daiktavardžio su priesaga -iškas; plius su neigiamu priešdėliu be-, pvz.: bedieviškas, bejėgiškas',
                 47: u'padarytas iš daiktavardžio su priesaga -inis; plius su neigiamu priešdėliu a-, pvz.: asimetrinis',
                 48: u'padarytas iš daiktavardžio su priesaga -iškas; plius su neigiamu priešdėliu a-, pvz.: asimetriškas',
                 49: u'padarytas iš daiktavardžio su priesaga -inis; plius su neigiamu priešdėliu ne-, pvz.: nepartinis',
                 50: u'padarytas iš daiktavardžio su -iškas; plius su neigiamu priešdėliu ne-, pvz.: nemokšiškas',
                 51: u'mažybinis, padarytas iš būdvardžio su priesaga -utis; plius su neigiamu priešdėliu ne-, pvz.: nekaltutis, nedidutis',
             }),
        }),
        (u'Derivacijos charakteristika', {
            10: (u'Deminutyviniai vediniai', {
                0: u'būdvardis tokių vedinių neturi',
                1: u'turi',
            }),
            11: (u'Daiktavardžio vediniai su ‑okas', {
                0: u'būdvardis tokių vedinių neturi',
                1: u'turi',
            }),
            12: (u'Daiktavardžio vediniai su ‑umas', {
                0: u'būdvardis tokių vedinių neturi',
                1: u'turi',
            }),
            13: (u'Daiktavardžio vediniai su ‑ybė', {
                0: u'būdvardis tokių vedinių neturi',
                1: u'turi',
            }),
            14: (u'Daiktavardžio vediniai su ‑ystė', {
                0: u'būdvardis tokių vedinių neturi',
                1: u'turi',
            }),
            15: (u'Prieveiksmio vediniai su ‑(i)ai', {
                0: u'būdvardis tokių vedinių neturi',
                1: u'turi',
            }),
            16: (u'Prieveiksmio vediniai su ‑yn', {
                0: u'būdvardis tokių vedinių neturi',
                1: u'turi',
            }),
            17: (u'Būdvardžio vediniai su priešdėliais apy‑ (api‑), po‑', {
                0: u'būdvardis tokių vedinių neturi',
                1: u'turi',
            }),
        }),
    ],

    # Skaitvardis
    3: [
        (u'Skaitvardžio ypatumai', {
             4: (u'Skyrius', {
                 1: u'kiekiniai',
                 2: u'dauginiai',
                 3: u'kuopiniai',
                 4: u'kelintiniai',
             }),
             5: (u'Linksnio ir skaičiaus valdymas', {
                 0: u'Nieko nevaldo',
                 1: u'Reikalauja vienaskaitos kilmininko',
                 2: u'Reikalauja daugiskaitos kilmininko',
                 3: u'Reikalauja dviskaitos',
             }),
        }),
        (u'Kaitybos charakteristika', {
             6: (u'Linksniavimo charakteristika', {
                  1: u'Žiūr. DLKG §711 psl. 245: vyr.g.vnsk.K: -o; vyr.g.dgsk.K: -ų; mot.g.vnsk.K: -os; mot.g.dgsk.K: -ų, pvz.: pusantro',
                  2: u'Žiūr. DLKG §711 psl. 245: vyr.g.vnsk.K: -io; vyr.g.dgsk.K: -ių; mot.g.vnsk.K: -ios; mot.g.dgsk.K: -ių, pvz.: pustrečio',
                  3: u'Kaip a (vyr.g.) ir o (mot.g.) linksniuočių būdvardžiai: vyr.g. - bdv linksniavimo 1 paradigma pgl (žiūr. DLKG §552 psl.179); mot.g. - bdv linksniavimo 6 paradigma pgl (žiūr. DLKG §556 psl.182), pvz.: dušimtas, pirmas, vienas, ketvirtas',
                  4: u'Kaip ia (vyr.g.) ir io (mot.g.) linksniuočių būdvardžiai: vyr.g. - bdv linksniavimo 3 paradigma pgl (žiūr. DLKG §552 psl.179); mot.g. - bdv linksniavimo 9 paradigma pgl (žiūr. DLKG §556 psl.184), pvz.: pirmesnis, vieneri',
                  5: u'Kaip ia (vyr.g.) ir io (mot.g.) linksniuočių būdvardžiai: vyr.g. - bdv linksniavimo 2 paradigma pgl (žiūr. DLKG §552 psl.179); mot.g. - bdv linksniavimo 7 paradigma pgl (žiūr. DLKG §556 psl.183), pvz.: pirmiausias, trečias',
                  6: u'Kaip a linksniuotės daiktavardžiai, linksniavimo 1 paradigma (žiūr.DLKG §119 psl.70), pvz.: abejetas, šimtas',
                  7: u'Žiūr. DLKG §718 psl. 247, pvz.: abu, du',
                  8: u'Žiūr. DLKG §719 psl. 247, pvz.: trys',
                  9: u'Žiūr. DLKG §720 psl. 247, pvz.: keturi',
                 10: u'dešimt(-s, -is): žiūr. DLKG §711psl.245, §721psl.248:; kaip mot.g. i linksniuotės dktv (plg. paslaptis: 9 paradigma pgl. žiūr DLKG §131psl.76; plius turi nelinksniuojamą formą dešimt(s), pvz.: dešimt(-s, -is)',
                 11: u'11-19: žiūr. DLKG §722 psl. 248, pvz.: vienuolika, devyniolika',
                 12: u'1000: žiūr. DLKG §723 psl.248: kaip (i)a linksniuotės daiktavardžiai, linksniavimo 3 paradigma pgl žiūr.DLKG §119 psl.71, pvz.: tūkstantis',
             }),
             7: (u'Giminės charakteristika', {
                 1: u'Turi vyr. ir mot. giminę, pvz.: pusantro, pustrečio',
                 2: u'Turi vyr., mot. ir bevardę giminę, pvz.: trečias',
                 3: u'Giminėmis nekaitomas (galima traktuoti, kad giminės kategorijos neturi ?); linksniuojamas įgyja daiktavardiškas vyr. g. formas, pvz.: abejetas, šimtas',
                 4: u'Giminėmis nekaitomas (galima traktuoti, kad giminės kategorijos neturi ?); linksniuojamas įgyja daiktavardiškas mot. g. formas; žiūr. DLKG §709, psl.244., pvz.: dešimt(is), vienuolika',
             }),
             8: (u'Skaičiaus charakteristika', {
                 1: u'Turi vienaskaitą ir daugiskaitą, pvz.: pusantro',
                 2: u'Skaičiumi nekaitomas; galima traktuoti, kad turi tik daugiskaitą, pvz.: vieneri, trys',
                 3: u'Skaičiumi nekaitomas; galima traktuoti, kad turi tik vienaskaitą (linksniuojamas įgyja vyr. g. vnsk. formas), pvz.: abejetas',
                 4: u'Skaičiumi nekaitomas; galima traktuoti, kad turi tik daugiskaitą (ar dviskaitą - čia priklauso nuo to kaip pažiūrėsi / sutraktuosi), pvz.: abu, du, dvi',
                 5: u'Skaičiumi nekaitomas; galima traktuoti, kad turi tik vienaskaitą (linksniuojamas įgyja mot. g. vnsk. formas), pvz.: vienuolika',
             }),
             9: (u'Laipsniavimo charakteristika', {
                 0: u'Laipsnio formų neturi (galima laikyti, kad laipsnio kategorija jam neturi prasmės), pvz.: pusantro',
                 1: u'Turi nelyg., aukštesnįjį, aukštėlesnįjį ir aukščiausiąjį laipsnius, pvz.: pirmas',
                 2: u'Žodynuose pateikiamas aukštesniojo laipsnio, taigi, traktuojamas kaip savarankiška leksema; galimas traktavimas, kad turi taip pat nelyg., aukštėlesn. ir aukščiaus. laipsnius, pvz.: pirmesnis',
                 3: u'Žodynuose pateikiamas aukščiausiojo laipsnio, taigi, traktuojamas kaip savarankiška leksema; galimas traktavimas, kad turi taip pat nelyg., aukštesn. ir aukštėlesnįjį laipsnius, pvz.: pirmiausias',
             }),
            10: (u'Apibrėžtumo (įvardžiuotinumo) charakteristika', {
                 0: u'Įvardžiuotinių formų neturi; galima laikyti, kad įvardžiuotinumo (apibrėžtumo) požymis neturi prasmės, pvz.: pusantro',
                 1: u'Įgyja tiek neįvardžiuotines,  tiek ir įvardžiuotines formas, pvz.: dušimtas',
            }),
        }),
        (u'Darybos charakteristika', {
            11: (None, {
                 1: u'trupmeninis sktv su dėmeniu pus- [DLKG §711 psl. 245, pvz.: pusantro',
                 2: u'kelintinis sktv iš atitinkamo kiekinio sktv kamieno, pvz.: aštuoniašimtas, trečias',
                 3: u'kelintinis sktv su savarankišku kamienu, pvz.: pirmas, antras',
                 4: u'kelintinio sktv aukštesniojo laipsnio forma iš nelyginamojo laipsnio, pvz.: pirmesnis',
                 5: u'kelintinio sktv aukščiausiojo laipsnio forma iš nelyg laipsnio, pvz.: pirmiausias',
                 6: u'kiekinis sktv su savarankišku kamienu, pvz.: vienas, du, trys, šimtas',
                 7: u'dauginis sktv iš atitinkamo kiekinio sktv kamieno, pvz.: vieneri',
                 8: u'kuopinis sktv iš atitinkamo kiekinio, pvz.: abejetas',
                 9: u'11-19: sktv su sandu -lika (DLKG §709 psl. 244), pvz.: vienuolika, devyniolika',
                10: u'10-90: kiekiniai dešimčių pavadinimai su sandu ()‑dešimt(-s, -is), pvz.: dešimt(-s, -is)',
            }),
        }),
        (u'Derivacijos charakteristika', {
            12: (u'Atitikmenų buvimas kituose skyriuose', {
                 1: u'Kiekinis, atitikmenų kituose skyriuose neturi, pvz.: pusantro',
                 2: u'Kelintinis, atitikmenų kituose skyriuose neturi, pvz.: dušimtas',
                 3: u'Kelintinis, turi atitikmenis kiekinių ir dauginių skaitvardžių skyriuose, pvz.: pirmas',
                 4: u'Kiekinis, turi atitikmenis dauginių ir kelintinių skaitvardžių skyriuose, pvz.: vienas',
                 5: u'Dauginis, turi atitikmenis kiekinių ir kelintinių skaitvardžių skyriuose, pvz.: vieneri',
                 6: u'Kuopinis, turi atitikmenis kiekinių ir dauginių skaitvardžių skyriuose, pvz.: abejetas',
                 7: u'Dauginis, turi atitikmenis kiekinių ir kuopinių skaitvardžių skyriuose, pvz.: abeji',
                 8: u'Kiekinis, turi atitikmenis kuopinių ir dauginių skaitvardžių skyriuose, pvz.: abu',
                 9: u'Kelintinis, turi atitikmenis kiekinių, dauginių ir kuopinių skaitvardžių skyriuose (t.y. visuose), pvz.: antras',
                10: u'Kiekinis, turi atitikmenis kelintin, dauginių ir kuopinių skaitvardžių skyriuose (t.y. visuose), pvz.: du, trys',
                11: u'Kuopinis, turi atitikmenis kiekinių, kelintinių ir dauginių skaitvardžių skyriuose (t.y. visuose), pvz.: dvejetas, trejetas',
                12: u'Dauginis, turi atitikmenis kiekinių, kelintinių ir kuopinių skaitvardžių skyriuose (t.y. visuose), pvz.: dveji, treji',
                13: u'Kiekinis, turi atitikmenį kelintinių skaitvardžių skyriuje, pvz.: dešimt, šimtas',
                14: u'Kelintinis, turi atitikmenį kiekinių skaitvardžių skyriuje, pvz.: dešimtas, tūkstantas',
            }),
            13: (u'Deminutyviniai vediniai', {
                1: u'Mažybinių vedinių neturi, pvz.: pusantro',
                2: u'Turi atitikmenis (=iš jų gali būti išvedami) daiktavardžius deminutyvus penktukas, penktukėlis ir t.t. iš penktas; dešimtukas iš dešimtis (dešimtas?);, pvz.: šimtelis iš šimtas',
            }),
            14: (u'Būdvardžio vedinių su -iškas galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            15: (u'Būdvardžio vedinių su -inis galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
            16: (u'Prieveiksmio vedinių su -in(i)ai galimumas', {
                0: u'tokių vedinių neturi',
                1: u'turi',
            }),
        }),
    ],
}


def main(lmdb):
    with open(lmdb) as f:
        for i, line in enumerate(f):
            line = line.strip().decode('cp1257')
            fields = line.split()
            params = map(int, fields[4:])
            lexeme, source, lemma, pos = fields[:4]
            lemma = lexeme if lemma == '-' else lemma
            pos = int(pos)
            if pos == 1 and params[22-4] == 3:
                print ('%s <- %s %s %s' % (lexeme, lemma, POS[pos], params)).encode('utf-8')
            if i > 100000: break


if __name__ == '__main__':
    lmdb = sys.argv[1]
    main(lmdb)
